### ISSUE TITLE
关于部分label无法设置为bool类型的问题

### ISSUE THREAD

**Issue by yaojia25** [CMHopeSunshine/amis-python#2]
大佬，最近用这个库遇到一个问题，在amis官方文档中，Group表单项组中可以配置input-text组件的lebel为false来关闭label的显示，
![image](https://user-images.githubusercontent.com/31342892/219966240-8307c9f9-200c-4e81-bb53-694a202660b6.png)
我在代码中给label赋值了False
![image](https://user-images.githubusercontent.com/31342892/219966305-e0999ac0-6997-4ac9-9ce8-7bd134168da4.png)
但是实际渲染的时候并没有生效，而是把布尔值False渲染为字符串“False”显示
![image](https://user-images.githubusercontent.com/31342892/219966391-7edb56c2-4689-443b-b559-fb8b5775e77a.png)
浏览器中检查对应输出的json如下：
![image](https://user-images.githubusercontent.com/31342892/219966475-616ae37e-8cc0-4183-b455-190a45b4240d.png)
这是没适配还是我写的有问题，希望能指点一下，谢谢！

**Comment by CMHopeSunshine** [comment]
稍候会发版修复这个问题，不过你可以不写label，或者将label赋值为None，这样也不会显示有label
```python
InputText(name='xxx', label=None)
```

**Comment by yaojia25** [comment]
好的，不过设置为None只是不显示label，但是还是会空出label的位置。

**Comment by CMHopeSunshine** [comment]
已修改，可以正常地设为False
